; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = esp32dev_ota

[env]
platform = espressif32
board = lolin32_lite
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
lib_deps =
  miguelbalboa/MFRC522
  dfrobot/DFRobotDFPlayerMini
build_flags =
  -DMFRC522_SPICLOCK=1000000

[env:esp32dev_usb]
build_src_filter =
  +<*>
  -<dumpinfo_main.cpp>
  -<dfplayer_test_main.cpp>
  -<gpio_function_test_main.cpp>
upload_protocol = esptool
upload_speed = 115200

[env:esp32dev_ota]
build_src_filter =
  +<*>
  -<dumpinfo_main.cpp>
  -<dfplayer_test_main.cpp>
  -<gpio_function_test_main.cpp>
upload_protocol = espota
upload_port = itt-sl58.local

[env:dumpinfo_usb]
build_src_filter =
  -<*>
  +<dumpinfo_main.cpp>
upload_protocol = esptool
upload_speed = 115200

[env:dfplayer_test_usb]
build_src_filter =
  -<*>
  +<dfplayer_test_main.cpp>
upload_protocol = esptool
upload_speed = 115200

[env:gpio_function_test_usb]
build_src_filter =
  -<*>
  +<gpio_function_test_main.cpp>
upload_protocol = esptool
upload_speed = 115200

[env:gpio_function_test_ota]
build_src_filter =
  -<*>
  +<gpio_function_test_main.cpp>
upload_protocol = espota
upload_port = itt-sl58.local

[env:dfplayer_test_ota]
build_src_filter =
  -<*>
  +<dfplayer_test_main.cpp>
upload_protocol = espota
upload_port = itt-sl58.local
