; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
lib_deps =
  miguelbalboa/MFRC522
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ILI9341
  dfrobot/DFRobotDFPlayerMini
  bodmer/TJpg_Decoder

upload_protocol = espota
upload_port = 192.168.178.101

[env:esp32dev_usb]
extends = env:esp32dev
upload_protocol = esptool
upload_port = /dev/ttyUSB0
